/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lfg.notifier.java;

public class App {

    public static void main(String[] args) {
        System.out.println("Initializing...");
        ScreenshotWatcher screenshotWatcher = new ScreenshotWatcher();
        Frontend frontend = new Frontend();
        frontend.setVisible(true);
        System.out.println("Initialized successfully!");

        frontend.setSearchStartCallback(() -> {
            screenshotWatcher.setWatchDirectory(frontend.getSelectedDir());
            System.out.println("Starting watch routine...");
            screenshotWatcher.watch(() -> { frontend.processFoundDungeon(); });
        });
    }
}
